#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: 大智若愚，举重若轻

# Short bio or description (displayed in the header)
description: ""

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: http://cc213.github.io/images/CC213.jpg

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble: 
  email: phoenix.w.2010@gmail.com
  facebook: 
  flickr: 
  github: cc213
  instagram: 
  linkedin: 
  pinterest: 
  rss: # just type anything here for a working RSS icon, make sure you set the "url" above!
  twitter: 
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"

# Your disqus shortname, entering this will enable commenting on posts
disqus: 

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: 

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://cc213.github.io/

# If you're hosting your site at a Project repository on GitHub pages 
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

# pagination
paginate: 10
paginate_
